-- MySQL Script generated by MySQL Workbench
-- ven. 27 déc. 2019 08:55:49 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema food
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `food` ;

-- -----------------------------------------------------
-- Schema food
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food` DEFAULT CHARACTER SET utf8 ;
USE `food` ;

-- -----------------------------------------------------
-- Table `food`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`category` ;

CREATE TABLE IF NOT EXISTS `food`.`category` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategory`),
  UNIQUE INDEX `idcategory_UNIQUE` (`idcategory` ASC));


-- -----------------------------------------------------
-- Table `food`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`product` ;

CREATE TABLE IF NOT EXISTS `food`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nutriscore_score` CHAR(10) NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `generic_name_fr` VARCHAR(1000) NOT NULL,
  `stores` VARCHAR(255) NOT NULL,
  `brands` VARCHAR(255) NOT NULL,
  `url` VARCHAR(1000) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `id_category_idx` USING BTREE (`category_id`),
  CONSTRAINT `id_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `food`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `food`.`substitute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food`.`substitute` ;

CREATE TABLE IF NOT EXISTS `food`.`substitute` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_to_substitute` INT NOT NULL,
  `product_substitued` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `product_substitued_idx` (`product_substitued` ASC),
  INDEX `product_to_substitute_idx` (`product_to_substitute` ASC),
  CONSTRAINT `product_to_substitute`
    FOREIGN KEY (`product_to_substitute`)
    REFERENCES `food`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_substitued`
    FOREIGN KEY (`product_substitued`)
    REFERENCES `food`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SET SQL_MODE = '';
DROP USER IF EXISTS toto;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'toto' IDENTIFIED BY 'tata';

GRANT ALL ON `food`.* TO 'toto';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
